apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-flask-deployment
  labels:
    app: simple-webapp-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-webapp-flask
  template:
    metadata:
      labels:
        app: simple-webapp-flask
    spec:
      containers:
      - name: simple-webapp-flask
        image: ghcr.io/mobola89/simple-webapp-flask:latest
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
        - name: FLASK_ENV
          value: production
